config/routes.rb
Blog::Application.routes.draw do
	scope "/blog/" do
		get "log_in" => "sessions#new", :as => "log_in"
		get "log_out" => "sessions#destroy", :as => "log_out"
		get "sign_up" => "users#new", :as => "sign_up"
		
		resources :users
		resources :sessions

		resources :posts do
			resources :comments
		end

		get "welcome/index"
		root 'posts#index'
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	before_save :encrypt_password
	
	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :username
	validates_uniqueness_of :username
	
	def self.authenticate( username, password )
		user = find_by_username( username )
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end
	
	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end	
	
	def set_admin
		self.admin = false
	end	
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :admin_rights
  
  private
	def current_user
		@current_user ||= User.find( session[:user_id] ) if session[:user_id]
	end

	def admin_rights
		@admin_rights ||= User.find( session[:user_id] ).admin if session[:user_id]
	end
	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find( params[ :post_id ] )
		@comment = @post.comments.create( params[ :comment ].permit( :commenter, :body ) )
		redirect_to post_path( @post )
	end
	
	def destroy
		if admin_rights
			@post = Post.find( params[ :post_id ] )
			@comment = @post.comments.find( params[ :id ] )
			@comment.destroy
			redirect_to post_path( @post )
		else
			redirect_to root_url
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end
	
	def new
		if admin_rights
			@post = Post.new
		else
			redirect_to root_url
		end
	end
	
	def create
		if admin_rights
			@post = Post.new( post_params )
			
			if @post.save
				redirect_to @post
			else
				render 'new'
			end
		else
			redirect_to root_url
		end
	end
	
	def show
		@post = Post.find( params[:id] )
	end
	
	def edit
		if admin_rights
			@post = Post.find( params[:id] )
		else
			redirect_to root_url
		end
	end
	
	def update
		if admin_rights
			@post = Post.find( params[:id] )
			
			if @post.update( post_params )
				redirect_to @post
			else
				render 'edit'
			end
		else
			redirect_to root_url
		end
	end
	
	def destroy
		if admin_rights
			@post = Post.find( params[:id] )
			@post.destroy
			
			redirect_to posts_path
		else
			redirect_to root_url
		end
	end
	
	private
		def post_params
			params.require(:post).permit(:title, :text)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
	user = User.authenticate( params[:username], params[:password] )
	
	if user
		session[:user_id] = user.id
		redirect_to root_url, :notice => "Logged in!"
	else
		flash.now.alert = "Invalid email or password"
		render "new"
	end
  end
  
  def destroy
	session[:user_id] = nil
	redirect_to root_url, :notice => "Logged Out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
	@user = User.new
  end
  
  def create
	@user = User.new( user_params )
	if @user.save
		redirect_to root_url, :notice => "Signed Up!"
	else
		render "new"
	end
  end
  
	private
		def user_params
			params.require(:user).permit(:username, :password, :password_confirmation)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
	<strong>
		Commenter:
	</strong>
	
	<%= comment.commenter %>
</p>

<p>
	<strong>
		Comment:
	</strong>
	
	<%= comment.body %>
</p>

<p>
	<strong>
		At:
	</strong>
	
	<%= comment.created_at %>
</p>

<% if admin_rights %>
	<p>
		<%= link_to 'Destroy Comment', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?'} %>
	</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for( [@post, @post.comments.build] ) do |f| %>
	<p>
		<%= f.label :commenter %><br>
		<% if current_user %>
			<%= f.text_field :commenter, :value => current_user.username %><br>
		<% else %>
			<%= f.text_field :commenter %><br>
		<% end %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %><br>
	</p>

	<p>
		<%= f.submit %><br>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>
	<meta charset="UTF-8">
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="user_nav">
	<% if current_user %>
		Logged in as 
		<% if admin_rights %><b><% end %>
			<%= current_user.username %>
		<% if admin_rights %></b><% end %>
		
		<%= link_to "Log Out", log_out_path %>
	<% else %>
		<%= link_to "Sign up", sign_up_path %>,
		<%= link_to "log in", log_in_path %> or
		<%= link_to "back to blog", root_url %>
	<% end %>
</div>

<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize( @post.errors.count, "error") %>
				prohibited this post from being saved:
			</h2>
			
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li>
						<%= msg %>
					</li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/posts/edit.html.erb
<h1>
	Editing Post
</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>
	Listing posts
</h1>

<% if admin_rights %>
	<p>
		<%= link_to 'New post', new_post_path %>
	</p>
<% end %>

<table>
	<tr>
		<th>
			Title
		</th>
		
		<th>
			Text
		</th>

		<th>
		</th>
		
		<% if admin_rights %>
			<th>
			</th>

			<th>
			</th>
		<% end %>
	</tr>
	
	<% @posts.each do |post| %>
		<tr>
			<td>
				(<%= post.comments.length %>)
				<%= post.title %>
			</td>

			<td>
				<%= truncate( post.text, :length => 20 ) %>
			</td>
			
			<td>
				<%= link_to 'Show', post %>
			</td>

			<% if admin_rights %>
				<td>
					<%= link_to 'Edit', edit_post_path( post ) %>
				</td>
			<% end %>

			<% if admin_rights %>
				<td>
					<%= link_to 'Destroy', post_path( post ), method: :delete, 
						data: { confirm: 'Are you sure?'} %>
				</td>
			<% end %>
		</tr>
	<% end %>
</table>

app/views/posts/new.html.erb
<h1>
	New Post
</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
	<strong>
		Title:
	</strong>
	
	<%= @post.title %>
</p>

<p>
	<strong>
		Text:
	</strong>
	
	<%= @post.text %>
</p>

<p>
	<strong>
		At:
	</strong>
	
	<%= @post.created_at %>
</p>


<h2>
	Comments:
</h2>

<%= render @post.comments %>

<h2>
	Add a comment:
</h2>

<%= render "comments/form" %>

<%= link_to 'Back', posts_path %>
	<% if admin_rights %>

	| <%= link_to 'Edit', edit_post_path( @post ) %>
<% end %>

app/views/users/new.html.erb
<h1>
	Sign Up
</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>
				Form is invalid
			</h2>
			
			<ul>
				<% for message in @user.errors.full_messages %>
					<li>
						<%= message %>
					</li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<p>
		*<%= f.label :username %><br />
		<%= f.text_field :username %><br />
	</p>

	<p>
		<%= f.label :email %><br />
		<%= f.text_field :email %><br />
	</p>
	
	<p>
		*<%= f.label :password %><br />
		<%= f.password_field :password %><br />
	</p>

	<p>
		*<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation %><br />
	</p>
	
	<p class="button">
		<%= f.submit %>
	</p>
	
	(* = required)
<% end %>

app/views/welcome/index.html.erb
<%= link_to "My Blog", controller: "posts" %>